name: DeployOnServer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create ssh key file
        run: echo ${{ secrets.PRODUCTION_DEPLOY_KEY }} > ssh_key
      - name: list
        run: ls -a
      - name: show key file
        run: cat ssh_key
      - name: Run deployment
        run: bash deploy.sh
      - name: delete ssh key file
        run: rm ssh_key
