name: DeployOnServer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create ssh key file
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: echo "$SSH_PRIVATE_KEY"
      - name: Run deployment
        run: bash deploy.sh
      - name: delete ssh key file
        run: rm ssh_key
