name: DeployOnServer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create ssh key file
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > /.ssh/id_rsa
      - name: Run deployment
        run: bash deploy.sh
      - name: delete ssh key file
        run: rm /.ssh/id_rsa
