name: DeployOnServer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: ls
      - name: Run deployment
        run: bash deploy.sh
